version: '3.8'

services:
  claude-code-companion:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "${VERSION:-docker-compose}"
    image: claude-code-companion:latest
    container_name: claude-code-companion
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # 配置文件挂载
      - ./config.docker.yaml:/app/config/config.yaml:ro
      # 日志目录挂载
      - ./logs:/app/logs
      # 可选：挂载自定义配置目录
      - ./config:/app/config:ro
    environment:
      # 环境变量示例，可以在配置文件中使用 ${ENV_VAR} 语法
      - TZ=Asia/Shanghai
      # API密钥可以通过环境变量传递
      # - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/admin/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - claude-network
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  # 可选：添加一个简单的监控服务
  # monitoring:
  #   image: prom/prometheus:latest
  #   container_name: claude-monitoring
  #   restart: unless-stopped
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   networks:
  #     - claude-network

networks:
  claude-network:
    driver: bridge

volumes:
  logs:
    driver: local
  config:
    driver: local